spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${mariadb.driver-class-name} 
    url: jdbc:mariadb://${mariadb.host}:${mariadb.port}/ums?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: ${mariadb.username}
    password: ${mariadb.password}
  data:
    redis:
      database: ${redis.database}
      host: ${redis.host}
      port: ${redis.port}
      # password: ${redis.password}
      lettuce:
        pool:
          min-idle: 1

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
